### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by sirio81** [KasparEtter/ef1p#6] opened 2021-08-06 15:26 UTC
```
LC_ALL=C grep -Fr 'Since the former term is also used to refer to' ef1p/
ef1p/pages/email/email.md:Since the former term is also used to refer to [email delivery vendors](#reputation),
```
Clicking on "email delivery vendors" link I end up to
https://explained-from-first-principles.com/email/#one-click-unsubscribe

**Comment by KasparEtter** [comment] 2021-08-08 09:55
Thanks for your report, I cannot reproduce your issue, though. "email delivery vendors" at https://explained-from-first-principles.com/email/#provider links to https://explained-from-first-principles.com/email/#reputation for me, which is what I intended. Do other green (internal) links for you? I will check tomorrow if expanding and closing boxes could interfere the correct scroll offset to the target location. If it's a JavaScript issue, it would be valuable to know what browser you are using.

**Closed as completed** 2021-09-12 13:25 UTC
